spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE # ou http://localhost:8081
          predicates:
            Path= /customers/**
        - id: r2
          uri: lb://INVENTORY-SERVICE # ou http://localhost:8082
          predicates:
            Path= /products/**
